spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
      routes:
        - id: listar-animales-service
          uri: ${LISTAR_ANIMALES_URL:http://localhost:8081}
          predicates:
            - Path=/api/animales/listar
          filters:
            - RewritePath=/api/animales/listar,/listar-animales
        - id: buscar-animal-service
          uri: ${BUSCAR_ANIMAL_URL:http://localhost:8082}
          predicates:
            - Path=/api/animales/buscar
          filters:
            - RewritePath=/api/animales/buscar,/buscar-animal
        - id: crear-animal-service
          uri: ${CREAR_ANIMAL_URL:http://localhost:8083}
          predicates:
            - Path=/api/animales/crear
          filters:
            - RewritePath=/api/animales/crear,/crear-animal
        - id: actualizar-animal-service
          uri: ${ACTUALIZAR_ANIMAL_URL:http://localhost:8084}
          predicates:
            - Path=/api/animales/actualizar
          filters:
            - RewritePath=/api/animales/actualizar,/actualizar-animal
        - id: borrar-animal-service
          uri: ${BORRAR_ANIMAL_URL:http://localhost:8085}
          predicates:
            - Path=/api/animales/borrar
          filters:
            - RewritePath=/api/animales/borrar,/borrar-animal
        - id: crear-dueno-service
          uri: ${CREAR_DUENO_URL:http://localhost:8086}
          predicates:
            - Path=/api/duenos/crear
          filters:
            - RewritePath=/api/duenos/crear,/crear-dueno
        - id: listar-duenos-service
          uri: ${LISTAR_DUENOS_URL:http://localhost:8087}
          predicates:
            - Path=/api/duenos/listar
          filters:
            - RewritePath=/api/duenos/listar,/listar-duenos
        - id: crear-veterinario-service
          uri: ${CREAR_VETERINARIO_URL:http://localhost:8088}
          predicates:
            - Path=/api/veterinarios/crear
          filters:
            - RewritePath=/api/veterinarios/crear,/crear-veterinario
        - id: listar-veterinarios-service
          uri: ${LISTAR_VETERINARIOS_URL:http://localhost:8089}
          predicates:
            - Path=/api/veterinarios/listar
          filters:
            - RewritePath=/api/veterinarios/listar,/listar-veterinarios
        - id: asignar-veterinario-service
          uri: ${ASIGNAR_VETERINARIO_URL:http://localhost:8090}
          predicates:
            - Path=/api/veterinarios/asignar
          filters:
            - RewritePath=/api/veterinarios/asignar,/asignar-veterinario

server:
  port: ${PORT:${SERVER_PORT:8080}}
