spring:
  application:
    name: asignar-veterinario-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/sistema_veterinario?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${SERVER_PORT:8090}
services:
  buscar-animal:
    url: ${BUSCAR_ANIMAL_URL:http://localhost:8082}